/**
 * Generates TOOLS.md from the tool definitions in src/tools (single source of truth).
 * Run with: npm run docs:tools
 */

import { writeFileSync } from 'node:fs';
import { z } from 'zod';
import { DEFAULT_TOOLSETS, TOOLSETS, TOOLSET_DESCRIPTIONS } from '../src/config.js';
import { ALL_TOOLS } from '../src/index.js';
import type { ToolDefinition } from '../src/tools/shared.js';

type AnyZod = z.ZodTypeAny;

/** Unwrap optional/default/effects wrappers to describe the underlying type. */
function describeType(schema: AnyZod): { type: string; required: boolean; defaultValue?: unknown } {
  let required = true;
  let defaultValue: unknown;
  let current: AnyZod = schema;

  for (;;) {
    if (current instanceof z.ZodOptional) {
      required = false;
      current = current.unwrap();
    } else if (current instanceof z.ZodDefault) {
      required = false;
      defaultValue = current._def.defaultValue();
      current = current._def.innerType;
    } else if (current instanceof z.ZodEffects) {
      current = current.innerType();
    } else {
      break;
    }
  }

  let type: string;
  if (current instanceof z.ZodString) type = 'string';
  else if (current instanceof z.ZodNumber) type = current.isInt ? 'integer' : 'number';
  else if (current instanceof z.ZodBoolean) type = 'boolean';
  else if (current instanceof z.ZodEnum) type = (current.options as string[]).map(o => `\`${o}\``).join(' \\| ');
  else if (current instanceof z.ZodUnion) type = (current.options as AnyZod[]).map(o => describeType(o).type).join(' \\| ');
  else if (current instanceof z.ZodRecord) type = 'object (map)';
  else if (current instanceof z.ZodArray) {
    const inner = current.element;
    type = inner instanceof z.ZodObject ? 'object[]' : `${describeType(inner).type}[]`;
  } else if (current instanceof z.ZodObject) type = 'object';
  else type = 'unknown';

  return { type, required, defaultValue };
}

function description(schema: AnyZod): string {
  // .describe() may sit on the wrapper or on the inner schema.
  let current: AnyZod | undefined = schema;
  while (current) {
    if (current.description) return current.description;
    current =
      current instanceof z.ZodOptional ? current.unwrap()
      : current instanceof z.ZodDefault ? current._def.innerType
      : current instanceof z.ZodEffects ? current.innerType()
      : undefined;
  }
  return '';
}

function paramTable(shape: z.ZodRawShape): string[] {
  return Object.entries(shape).map(([name, schema]) => {
    const info = describeType(schema as AnyZod);
    const def = info.defaultValue !== undefined ? ` Default: \`${JSON.stringify(info.defaultValue)}\`.` : '';
    const base = description(schema as AnyZod);
    const stop = base && def && !/[.!?)]$/.test(base) ? '.' : '';
    const text = `${base}${stop}${def}`.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
    return `| \`${name}\` | ${info.type} | ${info.required ? 'Yes' : 'No'} | ${text} |`;
  });
}

function behaviour(tool: ToolDefinition): string {
  const a = tool.annotations;
  if (a.destructiveHint) return 'Destructive (deletes or irreversibly changes data; clients should ask first)';
  if (a.readOnlyHint) return 'Read-only';
  return a.idempotentHint ? 'Writes (idempotent update)' : 'Writes (creates something)';
}

const lines: string[] = [
  '# Forgejo MCP Server: tools',
  '',
  '<!-- Generated by scripts/generate-tools-md.ts from src/tools. Do not edit by hand; run `npm run docs:tools`. -->',
  '',
  `${ALL_TOOLS.length} tools, all prefixed \`forgejo_\`, grouped into toolsets. ` +
    `The default toolsets (${DEFAULT_TOOLSETS.join(', ')}) give ${ALL_TOOLS.filter(t => t.toolset === 'meta' || DEFAULT_TOOLSETS.includes(t.toolset)).length} tools; ` +
    'enable more with `?toolsets=default,actions,...` (hosted) or `FORGEJO_TOOLSETS` (local), and hide every write tool with `?read_only=true` / `FORGEJO_READ_ONLY=true`.',
  '',
  'Every tool carries MCP annotations (read-only / destructive) so clients can decide when to ask before running it. ' +
    'Tools that return data accept `response_format`: `markdown` (default) or `json` (compact structured data).',
  '',
  '## Toolsets',
  '',
  '| Toolset | Default | Tools | Description |',
  '|---|---|---|---|',
  ...TOOLSETS.map(ts => {
    const count = ALL_TOOLS.filter(t => t.toolset === ts).length;
    const on = ts === 'meta' ? 'always' : DEFAULT_TOOLSETS.includes(ts) ? 'yes' : 'no';
    return `| [\`${ts}\`](#${ts}) | ${on} | ${count} | ${TOOLSET_DESCRIPTIONS[ts]} |`;
  }),
  '',
];

for (const toolset of TOOLSETS) {
  const tools = ALL_TOOLS.filter(t => t.toolset === toolset);
  if (!tools.length) continue;
  lines.push('---', '', `## ${toolset}`, '', `${TOOLSET_DESCRIPTIONS[toolset]}.`, '');
  for (const tool of tools) {
    lines.push(`### \`${tool.name}\``, '', `**${tool.title}**`, '', tool.description, '');
    lines.push(`- **Behaviour:** ${behaviour(tool)}`);
    if (tool.minVersion) lines.push(`- **Requires:** Forgejo ${tool.minVersion} or newer`);
    lines.push('');
    const rows = paramTable(tool.inputSchema);
    if (rows.length) lines.push('| Parameter | Type | Required | Description |', '|---|---|---|---|', ...rows, '');
    else lines.push('_No parameters._', '');
  }
}

writeFileSync('TOOLS.md', lines.join('\n'));
console.log(`Wrote TOOLS.md (${ALL_TOOLS.length} tools)`);
